"""ajusta FKs em atleta

Revision ID: 04ac958f4122
Revises: daf923701ba7
Create Date: 2025-08-12 13:24:10.822394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ac958f4122'
down_revision: Union[str, Sequence[str], None] = 'daf923701ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_unique_constraint(None, "centros_treinamento", ["pk_id"],)
    op.create_unique_constraint(None, "categorias", ["pk_id"],
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.create_foreign_key(None, 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.drop_constraint("uq_categorias_pk_id", "categorias", type_="unique")
    op.drop_constraint("uq_centros_treinamento_pk_id", "centros_treinamento", type_="unique")
    # ### end Alembic commands ###
